title: "Violetismo"
baseurl: ""
url: "https://violetismo.netlify.app"
collections:
  pages:
    output: true
    permalink: /:name/
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
