collections:
  - name: "paginas"
    label: "Páginas"
    files:
      - file: "index.md"
        label: "Inicio"
        name: "inicio"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Contenido", name: "body", widget: "markdown" }
      - file: "about.md"
        label: "Biografía"
        name: "bio"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Contenido", name: "body", widget: "markdown" }
  - name: "noticias"
    label: "Noticias"
    folder: "_posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Contenido", name: "body", widget: "markdown" }
