backend:
  name: git-gateway
  branch: master

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "paginas"
    label: "Páginas"
    files:
      - label: "Inicio"
        name: "inicio"
        file: "index.md"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Contenido", name: "body", widget: "markdown" }
